image: gcc:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - ./build/my_executable_test
  dependencies:
    - build
  artifacts:
    paths:
      - build/